kind: Service
apiVersion: v1
metadata: 
  name: nginx-lb
spec: 
  type: LoadBalancer
  selector: 
     project: expense
     environment: dev
     module: backend
  ports:
  - name: nginx-lb-port
    protocol: TCP
    port: 80
    targetPort: 80
